
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.04 at 09:14:07 AM EST 
//

/*
 * Ported to C# by Gert-Jan de Vries
 */

namespace SimpleNLG.Main.xmlrealiser.wrapper
{
    
    /**
     * <p>Java class for DocumentRealisation complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType name="DocumentRealisation">
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Document" type="{http://simplenlg.googlecode.com/svn/trunk/res/xml}DocumentElement"/>
     *         &lt;element name="Realisation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
	public class DocumentRealisation
	{
		protected internal XmlDocumentElement document;
		protected internal string realisation;
		protected internal string name;

        /**
         * Set / get the value of the document property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmlDocumentElement }
         *     
         */
		public virtual XmlDocumentElement Document
		{
			get
			{
				return document;
			}
			set
			{
				document = value;
			}
		}

        /**
         * Sets the value of the realisation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
		public virtual string Realisation
		{
			get
			{
				return realisation;
			}
			set
			{
				realisation = value;
			}
		}

	    /**
         * Set / get the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
		public virtual string Name
		{
			get
			{
				return name;
			}
			set
			{
				name = value;
			}
		}

	}

}