//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.04 at 09:14:07 AM EST 
//

/*
 * Ported to C# by Gert-Jan de Vries
 */

namespace SimpleNLG.Main.xmlrealiser.wrapper
{

    /**
     * This object contains factory methods for each 
     * Java content interface and Java element interface 
     * generated in the simplenlg.xmlrealiser.wrapper package. 
     * <p>An ObjectFactory allows you to programatically 
     * construct new instances of the Java representation 
     * for XML content. The Java representation of XML 
     * content can consist of schema derived interfaces 
     * and classes representing the binding of schema 
     * type definitions, element declarations and model 
     * groups.  Factory methods for each of these are 
     * provided in this class.
     * 
     */
	public class ObjectFactory
	{

        /**
         * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: simplenlg.xmlrealiser.wrapper
         * 
         */
		public ObjectFactory()
		{
		}

        /**
         * Create an instance of {@link NLGSpec }
         * 
         */
		public virtual NLGSpec createNLGSpec()
		{
			return new NLGSpec();
		}

        /**
         * Create an instance of {@link RequestType }
         * 
         */
		public virtual RequestType createRequestType()
		{
			return new RequestType();
		}

        /**
         * Create an instance of {@link RecordSet }
         * 
         */
		public virtual RecordSet createRecordSet()
		{
			return new RecordSet();
		}

        /**
         * Create an instance of {@link XmlPPPhraseSpec }
         * 
         */
		public virtual XmlPPPhraseSpec createXmlPPPhraseSpec()
		{
			return new XmlPPPhraseSpec();
		}

        /**
         * Create an instance of {@link XmlAdjPhraseSpec }
         * 
         */
		public virtual XmlAdjPhraseSpec createXmlAdjPhraseSpec()
		{
			return new XmlAdjPhraseSpec();
		}

        /**
         * Create an instance of {@link XmlDocumentElement }
         * 
         */
		public virtual XmlDocumentElement createXmlDocumentElement()
		{
			return new XmlDocumentElement();
		}

        /**
         * Create an instance of {@link XmlWordElement }
         * 
         */
		public virtual XmlWordElement createXmlWordElement()
		{
			return new XmlWordElement();
		}

        /**
         * Create an instance of {@link XmlAdvPhraseSpec }
         * 
         */
		public virtual XmlAdvPhraseSpec createXmlAdvPhraseSpec()
		{
			return new XmlAdvPhraseSpec();
		}

        /**
         * Create an instance of {@link XmlCoordinatedPhraseElement }
         * 
         */
		public virtual XmlCoordinatedPhraseElement createXmlCoordinatedPhraseElement()
		{
			return new XmlCoordinatedPhraseElement();
		}

        /**
         * Create an instance of {@link XmlNPPhraseSpec }
         * 
         */
		public virtual XmlNPPhraseSpec createXmlNPPhraseSpec()
		{
			return new XmlNPPhraseSpec();
		}

        /**
         * Create an instance of {@link DocumentRealisation }
         * 
         */
		public virtual DocumentRealisation createDocumentRealisation()
		{
			return new DocumentRealisation();
		}

        /**
         * Create an instance of {@link XmlVPPhraseSpec }
         * 
         */
		public virtual XmlVPPhraseSpec createXmlVPPhraseSpec()
		{
			return new XmlVPPhraseSpec();
		}

        /**
         * Create an instance of {@link XmlStringElement }
         * 
         */
		public virtual XmlStringElement createXmlStringElement()
		{
			return new XmlStringElement();
		}

        /**
         * Create an instance of {@link XmlSPhraseSpec }
         * 
         */
		public virtual XmlSPhraseSpec createXmlSPhraseSpec()
		{
			return new XmlSPhraseSpec();
		}

	}

}