//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.04 at 09:14:07 AM EST 
//

/*
 * Ported to C# by Gert-Jan de Vries
 */

namespace SimpleNLG.Main.xmlrealiser.wrapper
{

    /**
     * <p>Java class for AdjPhraseSpec complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType name="AdjPhraseSpec">
     *   &lt;complexContent>
     *     &lt;extension base="{http://simplenlg.googlecode.com/svn/trunk/res/xml}PhraseElement">
     *       &lt;sequence>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{http://simplenlg.googlecode.com/svn/trunk/res/xml}adjAdvPhraseAtts"/>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
	public class XmlAdjPhraseSpec : XmlPhraseElement
	{

		protected internal bool? iscomparative;
		protected internal bool? issuperlative;


        /**
         * Set / get the value of the iscomparative property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
		public virtual bool? ISCOMPARATIVE
		{
			get
			{
				return iscomparative;
			}
			set
			{
				iscomparative = value;
			}
		}
        
	    /**
         * Set / get the value of the issuperlative property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
		public virtual bool? ISSUPERLATIVE
		{
			get
			{
				return issuperlative;
			}
			set
			{
				issuperlative = value;
			}
		}
        
	}

}