using System.Collections.Generic;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.04 at 09:14:07 AM EST 
//

/*
 * Ported to C# by Gert-Jan de Vries
 */

namespace SimpleNLG.Main.xmlrealiser.wrapper
{

    /**
     * <p>Java class for CoordinatedPhraseElement complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType name="CoordinatedPhraseElement">
     *   &lt;complexContent>
     *     &lt;extension base="{http://simplenlg.googlecode.com/svn/trunk/res/xml}NLGElement">
     *       &lt;sequence>
     *         &lt;element name="coord" type="{http://simplenlg.googlecode.com/svn/trunk/res/xml}NLGElement" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{http://simplenlg.googlecode.com/svn/trunk/res/xml}CoordinatedPhraseAtts"/>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
	public class XmlCoordinatedPhraseElement : XmlNLGElement
	{

		protected internal IList<XmlNLGElement> coord;
		protected internal string conj;
		protected internal XmlPhraseCategory cat;
		protected internal bool? appositive;
		protected internal string conjunctiontype;
		protected internal string modal;
		protected internal bool? negated;
		protected internal XmlNumberAgreement? number;
		protected internal XmlPerson? person;
		protected internal bool? possessive;
		protected internal bool? progressive;
		protected internal bool? raisespecifier;
		protected internal bool? supressedcomplementiser;
		protected internal XmlTense? tense;

        /**
         * Set / get the value of the coord property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the coord property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCoord().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XmlNLGElement }
         * 
         * 
         */
		public virtual IList<XmlNLGElement> Coord
		{
			get
			{
				if (coord == null)
				{
					coord = new List<XmlNLGElement>();
				}
				return coord;
			}
		}


	    /**
         * Sets the value of the conj property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
		public virtual string Conj
		{
			get
			{
				if (ReferenceEquals(conj, null))
				{
					return "and";
				}
				else
				{
					return conj;
				}
			}
			set
			{
				conj = value;
			}
		}

        /**
         * Set / get the value of the cat property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmlPhraseCategory }
         *     
         */
		public virtual XmlPhraseCategory Cat
		{
			get
			{
				return cat;
			}
			set
			{
				cat = value;
			}
		}
        
        /**
         * Set / get the value of the appositive property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
		public virtual bool? APPOSITIVE
		{
			get
			{
				return appositive;
			}
			set
			{
				appositive = value;
			}
		}

        /**
         * Set / get the value of the conjunctiontype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
		public virtual string CONJUNCTIONTYPE
		{
			get
			{
				return conjunctiontype;
			}
			set
			{
				conjunctiontype = value;
			}
		}
        
        /**
         * Set / get the value of the modal property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
		public virtual string MODAL
		{
			get
			{
				return modal;
			}
			set
			{
				modal = value;
			}
		}

        /**
         * Set / get the value of the negated property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
		public virtual bool? NEGATED
		{
			get
			{
				return negated;
			}
			set
			{
				negated = value;
			}
		}

        /**
         * Set / get the value of the number property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmlNumberAgreement }
         *     
         */
		public virtual XmlNumberAgreement? NUMBER
		{
			get
			{
				return number;
			}
			set
			{
				number = value;
			}
		}

	    /**
         * Set / get the value of the person property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmlPerson }
         *     
         */
		public virtual XmlPerson? PERSON
		{
			get
			{
				return person;
			}
			set
			{
				person = value;
			}
		}

        /**
         * Set / get the value of the possessive property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
		public virtual bool? POSSESSIVE
		{
			get
			{
				return possessive;
			}
			set
			{
				possessive = value;
			}
		}
            
        /**
         * Set / get the value of the progressive property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
		public virtual bool? PROGRESSIVE
		{
			get
			{
				return progressive;
			}
			set
			{
				progressive = value;
			}
		}

        /**
         * Set / get the value of the raisespecifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
		public virtual bool? RAISESPECIFIER
		{
			get
			{
				return raisespecifier;
			}
			set
			{
				raisespecifier = value;
			}
		}

        /**
         * Set / get the value of the supressedcomplementiser property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
		public virtual bool? SUPRESSEDCOMPLEMENTISER
		{
			get
			{
				return supressedcomplementiser;
			}
			set
			{
				supressedcomplementiser = value;
			}
		}

        /**
         * Set / get the value of the tense property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmlTense }
         *     
         */
		public virtual XmlTense? TENSE
		{
			get
			{
				return tense;
			}
			set
			{
				tense = value;
			}
		}

	}

}