using System.Collections.Generic;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.04 at 09:14:07 AM EST 
//

/*
 * Ported to C# by Gert-Jan de Vries
 */

namespace SimpleNLG.Main.xmlrealiser.wrapper
{
        
    /**
     * <p>Java class for DocumentElement complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType name="DocumentElement">
     *   &lt;complexContent>
     *     &lt;extension base="{http://simplenlg.googlecode.com/svn/trunk/res/xml}NLGElement">
     *       &lt;sequence>
     *         &lt;element name="child" type="{http://simplenlg.googlecode.com/svn/trunk/res/xml}NLGElement" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{http://simplenlg.googlecode.com/svn/trunk/res/xml}docAtts"/>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
	public class XmlDocumentElement : XmlNLGElement
	{

		protected internal IList<XmlNLGElement> child;
		protected internal XmlDocumentCategory? cat;
		protected internal string title;

        /**
         * Gets the value of the child property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the child property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getChild().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XmlNLGElement }
         * 
         * 
         */
		public virtual IList<XmlNLGElement> Child
		{
			get
			{
				if (child == null)
				{
					child = new List<XmlNLGElement>();
				}
				return child;
			}
		}


        /**
         * Set / get the value of the cat property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmlDocumentCategory }
         *     
         */
		public virtual XmlDocumentCategory? Cat
		{
			get
			{
				return cat;
			}
			set
			{
				cat = value;
			}
		}
        
        /**
         * Set / get the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
		public virtual string Title
		{
			get
			{
				return title;
			}
			set
			{
				title = value;
			}
		}
        
	}

}