

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.04 at 09:14:07 AM EST 
//

/*
 * Ported to C# by Gert-Jan de Vries
 */

namespace SimpleNLG.Main.xmlrealiser.wrapper
{

    /**
     * <p>Java class for lexicalCategory.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;simpleType name="lexicalCategory">
     *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *     &lt;enumeration value="ANY"/>
     *     &lt;enumeration value="SYMBOL"/>
     *     &lt;enumeration value="NOUN"/>
     *     &lt;enumeration value="ADJECTIVE"/>
     *     &lt;enumeration value="ADVERB"/>
     *     &lt;enumeration value="VERB"/>
     *     &lt;enumeration value="DETERMINER"/>
     *     &lt;enumeration value="PRONOUN"/>
     *     &lt;enumeration value="CONJUNCTION"/>
     *     &lt;enumeration value="PREPOSITION"/>
     *     &lt;enumeration value="COMPLEMENTISER"/>
     *     &lt;enumeration value="MODAL"/>
     *     &lt;enumeration value="AUXILIARY"/>
     *   &lt;/restriction>
     * &lt;/simpleType>
     * </pre>
     * 
     */
	public enum XmlLexicalCategory
	{
		ANY,
		SYMBOL,
		NOUN,
		ADJECTIVE,
		ADVERB,
		VERB,
		DETERMINER,
		PRONOUN,
		CONJUNCTION,
		PREPOSITION,
		COMPLEMENTISER,
		MODAL,
		AUXILIARY
	}
    
}