//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.04 at 09:14:07 AM EST 
//

/*
 * Ported to C# by Gert-Jan de Vries
 */

namespace SimpleNLG.Main.xmlrealiser.wrapper
{
        
    /**
     * <p>Java class for NPPhraseSpec complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType name="NPPhraseSpec">
     *   &lt;complexContent>
     *     &lt;extension base="{http://simplenlg.googlecode.com/svn/trunk/res/xml}PhraseElement">
     *       &lt;sequence>
     *         &lt;element name="spec" type="{http://simplenlg.googlecode.com/svn/trunk/res/xml}NLGElement" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{http://simplenlg.googlecode.com/svn/trunk/res/xml}npPhraseAtts"/>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
	public class XmlNPPhraseSpec : XmlPhraseElement
	{

		protected internal XmlNLGElement spec;
		protected internal bool? adjectiveordering;
		protected internal bool? elided;
		protected internal XmlNumberAgreement? number;
		protected internal XmlGender? gender;
		protected internal XmlPerson? person;
		protected internal bool? possessive;
		protected internal bool? pronominal;


        /**
         * Set / get the value of the spec property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmlNLGElement }
         *     
         */
		public virtual XmlNLGElement Spec
		{
			get
			{
				return spec;
			}
			set
			{
				spec = value;
			}
		}
            
        /**
         * Set / get the value of the adjectiveordering property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
		public virtual bool? ADJECTIVEORDERING
		{
			get
			{
				return adjectiveordering;
			}
			set
			{
				adjectiveordering = value;
			}
		}
        
        /**
         * Set / get the value of the elided property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
		public virtual bool? ELIDED
		{
			get
			{
				return elided;
			}
			set
			{
				elided = value;
			}
		}

        /**
         * Set / get the value of the number property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmlNumberAgreement }
         *     
         */
		public virtual XmlNumberAgreement? NUMBER
		{
			get
			{
				return number;
			}
			set
			{
				number = value;
			}
		}

        /**
         * Set / get the value of the gender property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmlGender }
         *     
         */
		public virtual XmlGender? GENDER
		{
			get
			{
				return gender;
			}
			set
			{
				gender = value;
			}
		}

        /**
         * Set / get the value of the person property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmlPerson }
         *     
         */
		public virtual XmlPerson? PERSON
		{
			get
			{
				return person;
			}
			set
			{
				person = value;
			}
		}

        /**
         * Set / get the value of the possessive property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
		public virtual bool? POSSESSIVE
		{
			get
			{
				return possessive;
			}
			set
			{
				possessive = value;
			}
		}

	    /**
         * Set / get the value of the pronominal property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public virtual bool? PRONOMINAL
		{
			get
			{
				return pronominal;
			}
			set
			{
				pronominal = value;
			}
		}

	}

}