using System.Collections.Generic;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.04 at 09:14:07 AM EST 
//

/*
 * Ported to C# by Gert-Jan de Vries
 */

namespace SimpleNLG.Main.xmlrealiser.wrapper
{

    /**
     * <p>Java class for PhraseElement complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType name="PhraseElement">
     *   &lt;complexContent>
     *     &lt;extension base="{http://simplenlg.googlecode.com/svn/trunk/res/xml}NLGElement">
     *       &lt;sequence>
     *         &lt;element name="frontMod" type="{http://simplenlg.googlecode.com/svn/trunk/res/xml}NLGElement" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="preMod" type="{http://simplenlg.googlecode.com/svn/trunk/res/xml}NLGElement" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="compl" type="{http://simplenlg.googlecode.com/svn/trunk/res/xml}NLGElement" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="postMod" type="{http://simplenlg.googlecode.com/svn/trunk/res/xml}NLGElement" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="head" type="{http://simplenlg.googlecode.com/svn/trunk/res/xml}WordElement" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="cat" type="{http://simplenlg.googlecode.com/svn/trunk/res/xml}phraseCategory" />
     *       &lt;attribute name="discourseFunction" type="{http://simplenlg.googlecode.com/svn/trunk/res/xml}discourseFunction" />
     *       &lt;attribute name="appositive" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
	public abstract class XmlPhraseElement : XmlNLGElement
	{

		protected internal IList<XmlNLGElement> frontMod;
		protected internal IList<XmlNLGElement> preMod;
		protected internal IList<XmlNLGElement> compl;
		protected internal IList<XmlNLGElement> postMod;
		protected internal XmlWordElement head;
		protected internal XmlPhraseCategory cat;
		protected internal XmlDiscourseFunction? discourseFunction;
		protected internal bool? appositive;

        /**
         * Gets the value of the frontMod property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the frontMod property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFrontMod().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XmlNLGElement }
         * 
         * 
         */
		public virtual IList<XmlNLGElement> FrontMod
		{
			get
			{
				if (frontMod == null)
				{
					frontMod = new List<XmlNLGElement>();
				}
				return frontMod;
			}
		}
        /**
         * Gets the value of the preMod property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the preMod property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPreMod().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XmlNLGElement }
         * 
         * 
         */
		public virtual IList<XmlNLGElement> PreMod
		{
			get
			{
				if (preMod == null)
				{
					preMod = new List<XmlNLGElement>();
				}
				return preMod;
			}
		}
        /**
         * Gets the value of the compl property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the compl property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCompl().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XmlNLGElement }
         * 
         * 
         */
		public virtual IList<XmlNLGElement> Compl
		{
			get
			{
				if (compl == null)
				{
					compl = new List<XmlNLGElement>();
				}
				return compl;
			}
		}
        /**
         * Gets the value of the postMod property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the postMod property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPostMod().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XmlNLGElement }
         * 
         * 
         */
		public virtual IList<XmlNLGElement> PostMod
		{
			get
			{
				if (postMod == null)
				{
					postMod = new List<XmlNLGElement>();
				}
				return postMod;
			}
		}


        /**
         * Set / get the value of the head property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmlWordElement }
         *     
         */
		public virtual XmlWordElement Head
		{
			get
			{
				return head;
			}
			set
			{
				head = value;
			}
		}

        /**
         * Set / get the value of the cat property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmlPhraseCategory }
         *     
         */
		public virtual XmlPhraseCategory Cat
		{
			get
			{
				return cat;
			}
			set
			{
				cat = value;
			}
		}
        
        /**
         * Set / get the value of the discourseFunction property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmlDiscourseFunction }
         *     
         */
		public virtual XmlDiscourseFunction? DiscourseFunction
		{
			get
			{
				return discourseFunction;
			}
			set
			{
				discourseFunction = value;
			}
		}

        /**
         * Set / get the value of the appositive property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
		public virtual bool? Appositive
		{
			get
			{
				return appositive;
			}
			set
			{
				appositive = value;
			}
		}
        
	}

}