//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.04 at 09:14:07 AM EST 
//

/*
 * Ported to C# by Gert-Jan de Vries
 */

namespace SimpleNLG.Main.xmlrealiser.wrapper
{
        
    /**
     * <p>Java class for VPPhraseSpec complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType name="VPPhraseSpec">
     *   &lt;complexContent>
     *     &lt;extension base="{http://simplenlg.googlecode.com/svn/trunk/res/xml}PhraseElement">
     *       &lt;sequence>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{http://simplenlg.googlecode.com/svn/trunk/res/xml}vpPhraseAtts"/>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
	public class XmlVPPhraseSpec : XmlPhraseElement
	{

		protected internal bool? aggregateauxiliary;
		protected internal XmlForm? form;
		protected internal string modal;
		protected internal bool? negated;
		protected internal bool? passive;
		protected internal bool? perfect;
		protected internal XmlPerson? person;
		protected internal bool? progressive;
		protected internal bool? suppressgenitiveingerund;
		protected internal bool? supressedcomplementiser;
		protected internal XmlTense? tense;


        /**
         * Sets the value of the aggregateauxiliary property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
		public virtual bool? AGGREGATEAUXILIARY
		{
			get
			{
				return aggregateauxiliary;
			}
			set
			{
				aggregateauxiliary = value;
			}
		}

        /**
         * Sets the value of the form property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmlForm }
         *     
         */
		public virtual XmlForm? FORM
		{
			get
			{
				return form;
			}
			set
			{
				form = value;
			}
		}

        /**
         * Sets the value of the modal property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
		public virtual string MODAL
		{
			get
			{
				return modal;
			}
			set
			{
				modal = value;
			}
		}
            
        /**
         * Sets the value of the negated property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
		public virtual bool? NEGATED
		{
			get
			{
				return negated;
			}
			set
			{
				negated = value;
			}
		}
            
        /**
         * Set / get the value of the passive property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
		public virtual bool? PASSIVE
		{
			get
			{
				return passive;
			}
			set
			{
				passive = value;
			}
		}
            
        /**
         * Set / get the value of the perfect property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
		public virtual bool? PERFECT
		{
			get
			{
				return perfect;
			}
			set
			{
				perfect = value;
			}
		}

        /**
         * Set / get the value of the person property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmlPerson }
         *     
         */
		public virtual XmlPerson? PERSON
		{
			get
			{
				return person;
			}
			set
			{
				person = value;
			}
		}

        /**
         * Set / get the value of the progressive property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
		public virtual bool? PROGRESSIVE
		{
			get
			{
				return progressive;
			}
			set
			{
				progressive = value;
			}
		}

        /**
         * Set / get the value of the suppressgenitiveingerund property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
		public virtual bool? SUPPRESSGENITIVEINGERUND
		{
			get
			{
				return suppressgenitiveingerund;
			}
			set
			{
				suppressgenitiveingerund = value;
			}
		}
            
        /**
         * Set / get the value of the supressedcomplementiser property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
		public virtual bool? SUPRESSEDCOMPLEMENTISER
		{
			get
			{
				return supressedcomplementiser;
			}
			set
			{
				supressedcomplementiser = value;
			}
		}
            
        /**
         * Set / get the value of the tense property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmlTense }
         *     
         */
		public virtual XmlTense? TENSE
		{
			get
			{
				return tense;
			}
			set
			{
				tense = value;
			}
		}
        
	}

}