//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.04 at 09:14:07 AM EST 
//

/*
 * Ported to C# by Gert-Jan de Vries
 */

namespace SimpleNLG.Main.xmlrealiser.wrapper
{
        
    /**
     * <p>Java class for WordElement complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType name="WordElement">
     *   &lt;complexContent>
     *     &lt;extension base="{http://simplenlg.googlecode.com/svn/trunk/res/xml}NLGElement">
     *       &lt;sequence>
     *         &lt;element name="base" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{http://simplenlg.googlecode.com/svn/trunk/res/xml}wordAtts"/>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
	public class XmlWordElement : XmlNLGElement
	{

		protected internal string @base;
		protected internal XmlLexicalCategory cat;
		protected internal string id;
		protected internal bool? expletivesubject;
		protected internal bool? proper;
		protected internal XmlInflection? var;
		protected internal bool? canned;


        /**
         * Set / get the value of the base property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
		public virtual string Base
		{
			get
			{
				return @base;
			}
			set
			{
				@base = value;
			}
		}
            
        /**
         * Set / get the value of the cat property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmlLexicalCategory }
         *     
         */
		public virtual XmlLexicalCategory Cat
		{
			get
			{
				return cat;
			}
			set
			{
				cat = value;
			}
		}
            
        /**
         * Set / get the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
		public virtual string Id
		{
			get
			{
				return id;
			}
			set
			{
				id = value;
			}
		}
            
        /**
         * Set / get the value of the expletivesubject property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
		public virtual bool? EXPLETIVESUBJECT
		{
			get
			{
				return expletivesubject;
			}
			set
			{
				expletivesubject = value;
			}
		}
            
        /**
         * Set / get the value of the proper property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
		public virtual bool? PROPER
		{
			get
			{
				return proper;
			}
			set
			{
				proper = value;
			}
		}
            
        /**
         * Set / get the value of the var property.
         * 
         * @param value
         *     allowed object is
         *     {@link XmlInflection }
         *     
         */
		public virtual XmlInflection? Var
		{
			get
			{
				return var;
			}
			set
			{
				var = value;
			}
		}
            
        /**
         * Set / get the value of the canned property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
		public virtual bool? Canned
		{
			get
			{
				return canned;
			}
			set
			{
				canned = value;
			}
		}
        
	}

}